### ISSUE TITLE
Bump WordPress and PHP minimums

### ISSUE THREAD

**Issue by vikrampm1** [helen/action-wordpress-plugin-deploy#101]
Bump WP & PHP Minimums to the following
 
- [ ] WordPress to 5.7
- [ ] PHP to 7.4
- [ ] Remove any no-longer-needed conditional code for older version support.
- [ ] Take a look at adjusting our testing matrices, if applicable.
- [ ] Bump the minimums in plugin documentation and header fields.

**Comment by Sidsector9** [comment]
@vikrampm1 this repo isn't a WordPress plugin/extension that requires these changes.
I am closing this.
