### ISSUE TITLE
fatal: detected dubious ownership in repository at '/github/workspace'

### ISSUE THREAD

**Issue by Stiofan** [helen/action-wordpress-plugin-deploy#116]
When using a .gitattributes file (instead of a .distignore )  we got the following error when deploying the plugin:

```
➤ Copying files...
ℹ︎ Using .gitattributes
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

This folder is not in our repo, it seems to be a github default folder so...
Our repo: https://github.com/AyeCode/google-maps-api-key

This error seems to be appearing for a few other actions recently
https://github.com/robotology/gh-action-nightly-merge/issues/11
https://github.com/actions/checkout/issues/766

The solution seems to be to either use the .distignore file or you need to add this to your deploy script:
```
# See https://github.com/actions/checkout/issues/766
git config --global --add safe.directory "$GITHUB_WORKSPACE"
```

**Comment by Stiofan** [comment]
Any feedback on this?  I can make a pull request if required?  I'd prefer not to have to fork...

**Comment by DannyCooper** [comment]
I'm also getting this error, did you find a workaround @Stiofan?

**Comment by Stiofan** [comment]
> I'm also getting this error, did you find a workaround @Stiofan?

Yes, add a .distignore file to your repo, and add the things you don't want to be uploaded there, this makes it skip the problematic part of the code.
Example file: https://github.com/AyeCode/invoicing/blob/master/.distignore

Hopefully, they can still fix the issue though.

**Comment by DannyCooper** [comment]
Thanks for sharing a working solution!

**Comment by musamamasood** [comment]
@Stiofan Thank you for sharing the solution and save the day.

**Comment by nielslange** [comment]
Thanks for sharing the workaround, @Stiofan! 🙌

**Comment by alexminza** [comment]
This issue was closed but I still do encounter it: https://github.com/alexminza/wc-victoriabank/actions/runs/4707791867/jobs/8349876966

**Comment by nielslange** [comment]
> This issue was closed but I still do encounter it: https://github.com/alexminza/wc-victoriabank/actions/runs/4707791867/jobs/8349876966

Hello @alexminza 👋

On https://github.com/alexminza/wc-victoriabank/blob/7f950a72c096b17a95e24522480e04081d38f579/.github/workflows/action-wordpress-plugin-deploy.yml#L13, I saw that you're loading this dependency like this:

```
10up/action-wordpress-plugin-deploy@master
```

Looking at [the corresponding PR](https://github.com/10up/action-wordpress-plugin-deploy/pull/119), I see that the fix had been merged into `develop`.

If you load the dependency like this, the problem should be solved on your end:

```
10up/action-wordpress-plugin-deploy@develop
```

**Comment by alexminza** [comment]
Good observation @nielslange - thanks!
I would prefer using a stable version for plugin deployments - any chance this is going to be pushed to `master` soon?

**Comment by nielslange** [comment]
> any chance this is going to be pushed to master soon?

`develop` seems to be the new `master`. 🙈

- https://github.com/10up/action-wordpress-plugin-deploy/tree/develop: last updated on April 11, 2023
- https://github.com/10up/action-wordpress-plugin-deploy/tree/stable: last updated on August 16, 2022
- https://github.com/10up/action-wordpress-plugin-deploy/tree/master: last updated on March 13, 2020

@jeffpaul Can you clarify what's going on with `stable` and `master`?
