### ISSUE TITLE
Sync from GIT to SVN fails for tags

### ISSUE THREAD

**Issue by ymichel** [helen/action-wordpress-plugin-deploy#117]
**Describe the bug**
I have started to use your plugin. Unfortunately it fails with the following message:

Path '/home/runner/svn-geolocation/tags/refs/heads' is not a directory

And I don’t know how to overcome this.

Job is https://github.com/ymichel/Geolocation-Plugin/actions/runs/4262718472/jobs/7418555032

**Steps to Reproduce**

1. Go to Actions
2. Click on 'Run Workflow
3. Scroll down to 'messages’

**Expected behavior**
I can sync tags from GIT to SVN

**Additional context**
I have previously done it manual but also do not have all tags in GIT that exist in SVN.

**Comment by ymichel** [comment]
One more thing: This happens, if I manually trigger the action.

**Comment by jeffpaul** [comment]
@ymichel looks like the [latest action run](https://github.com/ymichel/Geolocation-Plugin/actions/runs/4460510421/jobs/7833697187) successfully deployed to https://wordpress.org/plugins/geolocation/, correct?  Are you still having problems here or can we close out this issue?

**Comment by ymichel** [comment]
Yes, like I said the issue occurred when executing from master but not from tagging.

**Comment by jeffpaul** [comment]
@ymichel you're only triggering the action when tagging, see https://github.com/ymichel/Geolocation-Plugin/blob/c0124069d05bbfe9ddcc0ed796c78e8a3e8e7768/.github/workflows/deploy.yml#L2-L5.

If you also want to have this happen on merges to `master`, then you'll need to add that to the workflow file.

**Comment by ymichel** [comment]
I initially tried with workflow_dispatch first but that was not working. I would have assumed, that this would take the latest tag or the tag history to sync git to svn. However, I managed to now use the tags to fire the event/action only. 
Don’t know if it was ever intended to work this way…

**Comment by jeffpaul** [comment]
@ymichel sounds like you're all set here?  If not, could you please share what additional assistance you might need?  Thanks!

**Comment by ymichel** [comment]
Well, it works now at tagging a particular state. However, I would have wanted to force the publish to SVN possibly with manually adding a version but it all sorted out and works now fine for me.
Issue can be closed.
