### ISSUE TITLE
Support a "DRY RUN" mode that can be used while testing

### ISSUE THREAD

**Issue by joemcgill** [helen/action-wordpress-plugin-deploy#121]
**Is your enhancement related to a problem? Please describe.**

While implementing this action in a mono-repo setup for the [Performance Lab plugin](https://github.com/WordPress/performance), we wanted to be able to do a dry run of the deployment workflow we created without actually pushing the committed changes to the WordPress SVN repo. To accomplish this we copied the `deploy.sh` file from this action into our repo and comment out the commit step while we were testing that our automated build/deploy process was working as expected.

**Describe the solution you'd like**

What would be better, is if this action supported a new `DEBUG` or `DRY_RUN` environment variable, which defaults to `false`, that would skip the final commit step when set to `true`. Ex:

```bash
if [[ "$DEBUG" != false ]]; then
  echo "➤ Committing files..."
  svn commit -m "Update to version $VERSION from GitHub" --no-auth-cache --non-interactive  --username "$SVN_USERNAME" --password "$SVN_PASSWORD"
else
  echo "➤ Debug mode: Files not committed."
fi
```

**Comment by jeffpaul** [comment]
Is there anything else that you would want to see/know when purposely NOT committing to SVN?  Like what the files/folders structure & resulting ZIP would be?

**Comment by joemcgill** [comment]
Preferably, I would want to see all of the output, including what the file structure is going to look like if they commit were to be completed. It’s possible that I would want to skip returning the zip file if the action is set up to return one, but I would want to at least see that the process was successful.

**Comment by mukeshpanchal27** [comment]
@joemcgill @jeffpaul I opened the PR that resolved the issue. Can you please take a look? Thanks!
