### ISSUE TITLE
Dry run is on by default

### ISSUE THREAD

**Issue by stephywells** [helen/action-wordpress-plugin-deploy#126]
**Describe the bug**
Since https://github.com/10up/action-wordpress-plugin-deploy/pull/122/files, the dry run is triggered and files are not pushed. Here's an example:
https://github.com/Strategy11/business-directory-plugin/actions/runs/4802423433/jobs/8545863161#step:4:45

**Steps to Reproduce**
1. Add the standard config in a workflow:
```
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@develop
```
2. Trigger the workflow.
3. No files are pushed, and the new dry run messages are shown in the log.

**Expected behavior**
The plugin should be pushed to SVN.

**Comment by stephywells** [comment]
The workaround is to add this to the config:
```
env:
  INPUT_DRY_RUN: false
```

**Comment by jeffpaul** [comment]
@stephywells thanks for the report, that was caught post-merge and will get resolved.

@mukeshpanchal27 you can utilize this issue for the PR you're working on.
