### ISSUE TITLE
svn: E155007: '/somedir/somefile' is not a working copy

### ISSUE THREAD

**Issue by overclokk** [helen/action-wordpress-plugin-deploy#131]
**Describe the bug**
I created and pushed the workflow file and got the error in the title at the `➤ Preparing files...` line.

**Steps to Reproduce**
I use TortoiseSVN
I don't know how to replicate but what I've done was to:

Click on "SVN Update" inside the folder of my project and I have no issue with TortoiseSVN.

So I updated some files in my project
Delete the content of the `trunk` folder in my machine
Copy the files in my project to the `trunk` folder in my machine
Then `add` the new files
Then commit to SVN

After the commit I got an error from TortoiseSVN (something about a folder not in sync) and need to re-update and commit again.

After that the workflow reach the `➤ Copying tag...` line.

**Additional context**
I don't kow why it happens and why the both `trunk` folder were not in sync.

Now I have to try and see if the TAG works, I'll let you know soon.

**Comment by overclokk** [comment]
Some update:
Now seams to work, I also check the name of the build folder if it was the same on GH action and on my pc because for building the final app I use a NPM script, I don't remember if at the start of this error it was the name of the folder the problem.

Right now I'm able to deploy to wp.org.

**Comment by vikrampm1** [comment]
@overclokk closing this issue as you're able to deploy now. Feel free to open it back if the issue persist or if you need any assistance.

**Comment by overclokk** [comment]
Thank you for now 😊
