### ISSUE TITLE
If the version already exists in SVN and generate-zip is configured, it should also generate the ZIP

### ISSUE THREAD

**Issue by sy-records** [helen/action-wordpress-plugin-deploy#132]
**Is your enhancement related to a problem? Please describe.**

The execution fails in Actions, but the zip package is not uploaded to the release asset, so the execution is repeated

**Describe the solution you'd like**

If the version already exists in SVN and generate-zip is configured, it should also generate the ZIP

<img width="499" alt="image" src="https://github.com/10up/action-wordpress-plugin-deploy/assets/33931153/e405b5c3-997d-4302-9dbb-84ac3df888c2">

**Comment by jeffpaul** [comment]
@sy-records thanks for the report and related PR, we'll get this off to the team for review and get back to you with any questions or otherwise head off to merge/release... thanks!
