### ISSUE TITLE
Use SVN copy from trunk to new tag folder to improve deploy times

### ISSUE THREAD

**Issue by danieliser** [helen/action-wordpress-plugin-deploy#140]
**Is your enhancement related to a problem? Please describe.**
Speed up deployment SVN commits by 50%.

**Describe the solution you'd like**
Currently it checks out the entire plugin (maybe not entirely), and then creates both the tag/{version} folder and updates trunk with new build files. Then commits it all at once to SVN.

Instead it should deploy only to trunk, then run an `svn cp` command to copy the trunk folder to `tags/{version}` which is near instant.

This is our manual deployment:

```
# Remove deleted files.
svn st | grep "!" | cut -d! -f2 | sed 's/^ *//' | xargs -n 500 -d "\n" -r svn rm
# MacOS
svn st | grep '^!' | cut -d! -f2 | sed 's/^ *//' | tr '\n' '\0' | xargs -0 svn rm

# Add new files.
svn st | grep ^? | cut -d? -f2 | sed 's/^ *//' | xargs -n 500 -d "\n" -r svn add
# MacOS
svn st | grep ^? | cut -d? -f2 | sed 's/^ *//' | tr '\n' '\0' | xargs -0 svn add

# Commit release changes.
svn ci -m "Updating code to release v1.18.2"

# Copy new version to tag folder from trunk.
svn copy https://plugins.svn.wordpress.org/plugin-name/trunk \
           https://plugins.svn.wordpress.org/plugin-name/tags/1.18.2 \
           -m "Tagging the 1.18.2 release"
```

Further if not already, it should only be checking out no depth then only getting trunk

I discuss all of this here in more details: https://danieliser.com/working-with-wordpress-org-svn-cheat-sheet/

**Comment by danieliser** [comment]
@jeffpaul I'd be open to helping, you can ping me on Post Status slack (if your there) & would like to discuss it.

Otherwise I can likely work it out and submit a PR if that's all you mean.

**Comment by helen** [comment]
Hello! Otto actually asked us to do it this way to avoid the second commit and load on .org, not sure if he would still want that today so you could ask, see https://github.com/10up/actions-wordpress/issues/4 for the history

**Comment by danieliser** [comment]
@helen 

> This prevents that middle moment when the readme in trunk points to a tag that you haven't created yet. Both trunk and the tagged version are sent at the same time.

That makes since.

> Despite what some think, this doesn't result in extra data use. Svn knows how to deal with local cp commands.

This seems highly inaccurate, pretty easy test to see that both transmission time & data sent are near doubled when doing this method.

That said the prior reason holds, short of a 3rd svn push to change the readme stable tag separately after tag copy, which makes even less since.
