### ISSUE TITLE
What wrong with my action script? 

### ISSUE THREAD

**Issue by code-with-mehedi** [helen/action-wordpress-plugin-deploy#141]
**Description:**

I have implemented an action script for my plugin. It shows the plugin deployed successfully but I don't see the changes in my code in wordpress.org SVN repo.

Here is my deploy.yml code
`name: Deploy to WordPress.org
on:
  push:
    tags:
      - '*'
    branches:
      - master
jobs:
  deploy-plugin:
    name: Deploy Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          npm install
          npm run build
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: storegrowth-sales-booster
          VERSION: 1.0.0`

**Comment by jeffpaul** [comment]
@code-with-mehedi can you please provide a link to your workflow file / GitHub Action run for us to better triage for you?

**Comment by code-with-mehedi** [comment]
@jeffpaul Thanks for your quick response. However, I have found the issue and that was related to the version number. So I am going to close this issue.
