### ISSUE TITLE
svn: E000104: Error running context: Connection reset by peer

### ISSUE THREAD

**Issue by iftakharul-islam** [helen/action-wordpress-plugin-deploy#156]
![Image](https://github.com/user-attachments/assets/8786d824-340f-42bd-b241-868188458454)

**Describe the bug**

All credentials are correctly placed 
Every steps completed it took 50+ min
But commit failed couple of times

Sometimes it gives this response 
Error: Process completed with exit code 1.

What's the issue here ?

**Comment by helen** [comment]
You need to link to the workflow/yml file and preferably also link to the action run you screenshotted with full logs so folks can troubleshoot, there's not enough information here. Though from your screenshot the error appears to be after over 17,000 lines of output so I have a feeling whatever you've done is trying to commit many many files and probably isn't what you want.

**Comment by iftakharul-islam** [comment]
Here is the [workflow](https://github.com/weDevsOfficial/wp-project-manager/actions/runs/12274421764/workflow)

You can check the running logs 
[run 1 ](https://github.com/weDevsOfficial/wp-project-manager/actions/runs/12274421764)
[run 2](https://github.com/weDevsOfficial/wp-project-manager/actions/runs/12273161087/job/34243390932)

**Comment by helen** [comment]
If you look at the full log you'll see that whatever build process you're running is generating an enormous number of files to be committed and therefore transmitted, mostly in vendor directories. Incredibly unlikely that many files will ever transfer successfully. You need to reevaluate what you're doing in your build process to see if you can reduce that for the sake of every .org user installing your plugin and in particular why there's a subfolder named zipfile in both trunk and tag that's being committed, that seems unnecessary. This action itself is doing what it's supposed to do.

**Comment by iftakharul-islam** [comment]
Oh!! problem with zipfile subfolder checking that.

**Comment by iftakharul-islam** [comment]
Thanks, @helen !
Issue was with the subfolder created by the zip-action some other unwanted files . It's resolved now.
