### ISSUE TITLE
Bug: Access to '/!svn/me' forbidden

### ISSUE THREAD

**Issue by jakubmikita** [helen/action-wordpress-plugin-deploy#33]
**Describe the bug**
Action just throws:

```
➤ Committing files...
svn: E175013: Commit failed (details follow):
svn: E175013: Access to '/!svn/me' forbidden
```

**Additional context**
See the [action log](https://github.com/BracketSpace/Notification-bbPress/runs/550986399?check_suite_focus=true).

**Comment by igorchernenko92** [comment]
Hi
I had the same issue
need to make sure the correct details have been set within the "secrets" in repo settings
issue for me was that I wrote the value for SVN_USERNAME wrong...its important to put proper attention on the writing...uppercase, lowercase etc

**Comment by helen** [comment]
@Kubitomakita In addition to double checking the username/password secrets, be sure that the user in question has been added as a committer to the plugin and you've tried again after maybe 10-15 minutes to be sure the permissions have taken effect on .org.

**Comment by jakubmikita** [comment]
Double checked the credentials and committer status, but this might be related to #32

**Comment by jakubmikita** [comment]
I found it... even when my username is `CapiTalized` SVN expects it to be `capitalized` for some reason...

**Comment by helen** [comment]
Glad you got that sorted! Might be worth documenting or linking to a .org resource about it if it keeps coming up.

**Comment by thejaydip** [comment]
I had the same issue. Any solution ?
![issue](https://user-images.githubusercontent.com/46511743/119252613-e08c2180-bbca-11eb-8839-6b498cf89887.png)

**Comment by jeffpaul** [comment]
@thejaydip have you checked the username/password secrets in your GitHub repo, checked that the user is a committer on the plugin on WP.org, and checked the capitalization of the username as referenced above?
