### ISSUE TITLE
How to execute composer command during build?

### ISSUE THREAD

**Issue by shivapoudel** [helen/action-wordpress-plugin-deploy#38]
We do not include `languages/<plugin-name>.pot` within git repository due to merge conflicts received time and again but auto generates them with the command `npm run build` which also executes `wp i18n` command during the build. How to execute composer script during the build action and add those files for the GitHub action?

Ref: https://github.com/wpeverest/everest-forms/blob/develop/package.json#L13

**Comment by shivapoudel** [comment]
@helen Since ZIP generation is possible now! Please give a look at this `npm run build` process for POT generation. Additionally, the generated POT will differ for assets deploy action so we need to exclude that POT file check during the process too.

**Comment by helen** [comment]
@shivapoudel ZIP uploading is still not working unfortunately :( As for the POT generation, you can run `npm run build` directly in the workflow for the deploy and not run build for the asset updater. Is there something else I'm missing there?

**Comment by shivapoudel** [comment]
@helen I am also giving a look on ZIP generation as I also triggered this warning:
```
##[warning]Unexpected input 'generate-zip', valid inputs are ['']
```

https://github.com/wpeverest/restaurantpress/runs/711110582?check_suite_focus=true

UPDATED: Found some issue log here https://github.com/actions/runner/issues/499

**Comment by shivapoudel** [comment]
@helen regarding the asset updater. If we ignore POT file generation in Github repo and during the release run `npm run build` will only generate a POT file using `wp i18n` via composer then deploy plugin assets will not work because it will act as POT file was deleted. Similar logic if we also remove minified JS and won't include CSS just SCSS files.

Additionally, haven't tried but should we need composer and PHP library installation in Docerfile OR Github action will handle that process automatically as in the PHP setup for action I found composer is preinstalled.

**Comment by helen** [comment]
Oh right, I forgot about that build complication again. Composer should be preinstalled, I use it for some workflows, not sure what you're asking there? I suppose you would probably want to run `composer install` in the workflow file.

**Comment by shivapoudel** [comment]
@helen The simple answer is I don't prefer adding POT files, modification JS and CSS files in Github repos which we will generate during the deploy process through this action. Is there any we can ignore those checks during the readme/screenshot update action which is simply my scenario.

**Comment by helen** [comment]
@shivapoudel Still thinking through this, and I have two questions.

First, why are you generating POT files for .org plugins on your own? I realized I hadn't been thinking about that scenario for this particular action because I rely on .org to generate them via language packs instead. Is there any reason to still be generating yourself?

For CSS and JS files, I personally would not want to ignore changes due to build process, as I would want to know that something has changed. What's changing between releases there that you feel comfortable ignoring?

**Comment by shivapoudel** [comment]
@helen both answers are due to heavy merge conflict... while working in a small group of people (approx 25) this kind of scenario occurs and we have to switch some kind of good workflow which includes ignoring POT file generation and production build script file generation. Additionally, being an old member since few years back I have to take care of all the difficulty and among that is merge conflict as far as I know.

**Comment by helen** [comment]
Hmmm I don't think I really understand this still, why are you generating a POT file at all? And if you're not committing those built files how are there merge conflicts?

**Comment by shivapoudel** [comment]
@helen Yeah! you are right if I don't commit those built files and there is no any merge conflict. But I am not talking about the merge conflicts issue, it's all about plugin asset/readme update using [this action](https://github.com/10up/action-wordpress-plugin-asset-update).

I receive this kind of failed step https://github.com/wpeverest/everest-forms/runs/682752668?check_suite_focus=true#step:4:394 because the POT file was found modified during the deployment as GitHub repo lacks it and only during the build we generate that file for wp.org plugin repository.

![image](https://user-images.githubusercontent.com/3774827/83093191-b179c780-a0be-11ea-9e6b-be1af304c58a.png)

**Comment by shivapoudel** [comment]
Completely related to #16 so will be tracking progress there. We build a build in a custom directory so all the src files of ES6 are not included and wanted to push only the `build/plugin-slug`. 

@helen This way we will not get merge conflict of POT files as well as scripts files as we will not be shipping development files overall. In my opinion this direction will benefit latest plugin development approach, you can generate a cuatom Gutenberg block example plugin and there also exists `dist` folder which is pushed to wp.org but not `src` directory used for bundler like webpack.
