### ISSUE TITLE
deploy action fails with no information

### ISSUE THREAD

**Issue by deanshmuel** [helen/action-wordpress-plugin-deploy#48]
Hi, 
Im trying to deploy my wordpress plugin to svn using your deploy action but it keeps on constantly failing, I need help locating my problem. 

the output my action yields:
 Wordpress plugin deploy1s
Set the SVN_USERNAME secret
##[warning]Unexpected input(s) 'SVN_PASSWORD', 'SVN_USERNAME', 'SLUG', valid inputs are ['entryPoint', 'args', 'generate-zip']
Run 10up/action-wordpress-plugin-deploy@stable
/usr/bin/docker run --name cb48c56363b5574ade95f88091aa29529a_629cdb --label 8118cb --workdir /github/workspace --rm -e INPUT_SVN_PASSWORD -e INPUT_SVN_USERNAME -e INPUT_SLUG -e INPUT_GENERATE-ZIP -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/eko-wp-plugin/eko-wp-plugin":"/github/workspace" 8118cb:48c56363b5574ade95f88091aa29529a  "false"
allexport      	off
braceexpand    	on
emacs          	off
errexit        	on
errtrace       	off
functrace      	off
hashall        	on
histexpand     	off
history        	off
ignoreeof      	off
interactive-comments	on
keyword        	off
monitor        	off
noclobber      	off
noexec         	off
noglob         	off
nolog          	off
notify         	off
nounset        	off
onecmd         	off
physical       	off
pipefail       	off
posix          	off
privileged     	off
verbose        	off
vi             	off
xtrace         	off
Set the SVN_USERNAME secret

(for this step, and i fails)
the step in my yml file looks like that:
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install php dependencies
      uses: php-actions/composer@v2
      with:
        dev: no
    - name: Install npm packages and build
      run: |
        npm install
        npm run build
    
  deploy-svn:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: create git tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Wordpress plugin deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}

any help please?
thanks,
Dean

**Comment by helen** [comment]
@deanshmuel Did you resolve this? It looks like you need to set those secrets in your repository. I need to take a look at whether we need to define these as expected inputs.
