### ISSUE TITLE
Repo with no images gets SVN error

### ISSUE THREAD

**Issue by Lewiscowles1986** [helen/action-wordpress-plugin-deploy#57]
**Describe the bug**

```
svn: E155010: The node '/github/svn-enable-svg-uploads/assets/*.png' was not found.
'assets/*.png' is not under version control
'assets/*.jpg' is not under version control
svn: E155010: The node '/github/svn-enable-svg-uploads/assets/*.jpg' was not found.
```

**Steps to Reproduce**

1. Use this action with a github repo without images
2. Observe the error message in action logs

**Expected behavior**

Only apply checks if such files exist

**Additional context**

I do not know if this is why SVN failed, or if I have done something else silly, but noticing it was enough to distract me.

**Comment by jeffpaul** [comment]
@Lewiscowles1986 do you have images on WP.org SVN that aren't mirrored in your GitHub repo?

**Comment by helen** [comment]
They're warnings from #40, I noticed them but haven't done anything about it. Probably a matter of suppression or doing an actual find + targeted propset.

**Comment by Lewiscowles1986** [comment]
Oh I have a fix in https://github.com/10up/action-wordpress-plugin-deploy/pull/56 now. I could break it out to standalone PR

**Comment by Lewiscowles1986** [comment]
@jeffpaul I do not in this case (where I am seeing this happen)

**Comment by jeffpaul** [comment]
@Lewiscowles1986 would be more ideal to break out those changes from #56 into a separate PR so we can track these issues/PRs in their own right (especially since #56 is targeting something else as well).

**Comment by Lewiscowles1986** [comment]
Apologies for not breaking out sooner @jeffpaul
