### ISSUE TITLE
Add output parameters for plugin ZIP path and name

### ISSUE THREAD

**Issue by ocean90** [helen/action-wordpress-plugin-deploy#60]
**Is your enhancement related to a problem? Please describe.**
When the repository name doesn't match the plugin's slug you can set the `SLUG` env variable. This one is also used for plugin ZIP if `generate-zip` is set. This means you can't use the `asset_path` and `asset_name` values as shown in the readme example.  

**Describe the solution you'd like**
I'd like to have the action returning the path and ZIP file as [output parameters](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-run-steps-actions) which can be consumed by follow-up actions like `actions/upload-release-asset`.

**Describe alternatives you've considered**
Replacing `${{ github.event.repository.name }}` with the hardcoded value for the slug.

**Comment by madurapa** [comment]
It would be nice to have this enhancement +1

**Comment by shivapoudel** [comment]
Any help on raising PR for this enhancement is appreciated :)

**Comment by helen** [comment]
Fixing this in #74 by adding a `zip-path` output param, not adding a name one for the moment because it can be customized to your heart's desire in the workflow file, though I will take the argument that most people are copy-pasting so the documentation may benefit from a specific example.
