### ISSUE TITLE
Error in the Build phase

### ISSUE THREAD

**Issue by sanbec** [helen/action-wordpress-plugin-deploy#61]
**Describe your question**
I
I'm trying with the yml «Deploy on publishing a new release and attach a ZIP file to the release» but i get this error at Build phase: Can you help me? Thanks!

  npm install
  npm run build
  shell: /bin/bash -e {0}
npm WARN saveError ENOENT: no such file or directory, open '/home/runner/work/manage-admin-columns/manage-admin-columns/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/runner/work/manage-admin-columns/manage-admin-columns/package.json'
npm WARN manage-admin-columns No description
npm WARN manage-admin-columns No repository field.
npm WARN manage-admin-columns No README data
npm WARN manage-admin-columns No license field.

up to date in 0.21s
found 0 vulnerabilities

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/runner/work/manage-admin-columns/manage-admin-columns/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/work/manage-admin-columns/manage-admin-columns/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-01-02T22_34_25_185Z-debug.log
Error: Process completed with exit code 254.

**Comment by helen** [comment]
I'm assuming this is for https://github.com/sanbec/manage-admin-columns (please link next time). It looks like there is no build process, so it's telling you that there is no package.json in which to find a build command. You should remove this step:

```
    - name: Build
      run: |
        npm install
        npm run build
```

**Comment by sanbec** [comment]
Thank you very much, that was the problem. The truth is that I do not understand what could be built, but that is another matter.
