### ISSUE TITLE
Version is not updated when running Github Action

### ISSUE THREAD

**Issue by dalenguyen** [helen/action-wordpress-plugin-deploy#65]
**Describe the bug**

When running Github Action, it keeps getting my old version of the plugin which returns an error when deploying to WordPress Plugin Directory

**Steps to Reproduce**

This is the failed actions: https://github.com/dalenguyen/firebase-wordpress-plugin/runs/1801687516?check_suite_focus=true

I tried with a different version of the tag, but it keeps the old one.  

![image](https://user-images.githubusercontent.com/14116156/106390052-8a456980-63b4-11eb-93f3-e8fd90e311fb.png)

When running, it retrieves the old version: 

![image](https://user-images.githubusercontent.com/14116156/106390066-9d583980-63b4-11eb-8cd3-8634417f9ef5.png)

**Expected behavior**

Github Actions passed

**Additional context**

**Comment by jeffpaul** [comment]
@dalenguyen the action is likely stripping the preceding `v` from `v0.8.0`, so you'll need to try `0.8.1` or something similar to see things work as expected.

**Comment by jeffpaul** [comment]
Also note that the `VERSION` variable is really [only recommended for testing purposes](https://github.com/10up/action-wordpress-plugin-deploy#optional-environment-variables):
> `VERSION` - defaults to the tag name; do not recommend setting this except for testing purposes.

**Comment by jeffpaul** [comment]
@dalenguyen is there anything else we can help you with on this or can we close the issue?

**Comment by dalenguyen** [comment]
Yes, I can close it. Thanks for your help.
