### ISSUE TITLE
Do you push docker image to any public registry?

### ISSUE THREAD

**Issue by sztwiorok** [helen/action-wordpress-plugin-deploy#68]
I want to test this action on my PC, is there any way to pull this image?

I have tried to pull it from the GitHub registry:
`docker pull docker.pkg.github.com/10up/action-wordpress-plugin-deploy:1.5.0`
but it looks like I don't have permission
`Error response from daemon: repository docker.pkg.github.com/10up/action-wordpress-plugin-deploy not found`

Can you send me a link to DockerHub with this image?

**Comment by dinhtungdu** [comment]
@sztwiorok we don't push the image of this action to Docker Hub, so I can't send you a link. But you can clone/download this action and build the image yourself, it uses `debian:stable-slim` so it won't take long.

**Comment by sztwiorok** [comment]
thanks for your help

**Comment by sztwiorok** [comment]
can you set this image as public?
https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#configuring-visibility-of-container-images-for-an-organization

**Comment by dinhtungdu** [comment]
@sztwiorok this is the action repo so there isn't any image built for this repository. Images are built and stored in repositories using this action.

Also, I checked the packages tab of 10up, all packages that belong to public repositories are public already.

**Comment by helen** [comment]
This doesn't spin up its own container anymore, for local testing there's https://github.com/nektos/act (also in reality it's "just" a Bash script).
