### ISSUE TITLE
SVN commit failed: Directory out of date

### ISSUE THREAD

**Issue by shivapoudel** [helen/action-wordpress-plugin-deploy#71]
@helen @jeffpaul We receive SVN commit failed: Directory out of date issue recently. You can see this failed action https://github.com/themegrill/suffice-toolkit/runs/3016789941?check_suite_focus=true#step:5:269 
![image](https://user-images.githubusercontent.com/3774827/124888469-db0d5e00-dff5-11eb-8964-7daafe0a6db5.png)

**Comment by jeffpaul** [comment]
@shivapoudel you'll want to update this line from `master` to `stable`: https://github.com/themegrill/suffice-toolkit/blob/8849a02c452fff95cfaa1e14bb267f24c3da0a55/.github/workflows/main.yml#L17

It looks like you have a lot of attempts at tagging 1.0.5: https://github.com/themegrill/suffice-toolkit/actions/workflows/main.yml?query=branch%3A1.0.5

Of those attempts I do see one success: https://github.com/themegrill/suffice-toolkit/actions/workflows/main.yml?query=is%3Asuccess as part of this commit: https://github.com/themegrill/suffice-toolkit/commit/f7730bb9937f44c8038b87a1f99739e706e9e190

And it looks like that was sent over to SVN: https://plugins.trac.wordpress.org/log/suffice-toolkit/ but unfortunately you had not updated the version/stable tag in your plugin to 1.0.5 so WP.org is still showing 1.0.4.

At this point you'll want to update your plugin version/stable tag to 1.0.5 and use https://github.com/10up/action-wordpress-plugin-asset-update to push across that readme/plugin change to WP.org.

Alternatively you can update your plugin version/stable tag to 1.0.6 and then tag/release that on GitHub and the deploy action should kick in and update WP.org.

**Comment by shivapoudel** [comment]
This fixes the issue. Thanks @jeffpaul :)
