### ISSUE TITLE
Build failing with docker error. 

### ISSUE THREAD

**Issue by spacedmonkey** [helen/action-wordpress-plugin-deploy#73]
**Describe the bug**
In my [repo](https://github.com/spacedmonkey/wp-rest-blocks/), I using this action. 

I am seeing [builds](https://github.com/spacedmonkey/wp-rest-blocks/runs/3334672627?check_suite_focus=true#step:2:23) failing with the following error 

>   Reading package lists...
  E: The repository 'http://security.debian.org/debian-security stable/updates Release' does not have a Release file.
  The command '/bin/sh -c apt-get update 	&& apt-get install -y subversion rsync git zip 	&& apt-get clean -y 	&& rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Expected behavior**

**Additional context**

**Comment by kurudrive** [comment]
I am faithing with this probrem too.

**Comment by Stiofan** [comment]
Getting this same error also.

**Comment by mrwweb** [comment]
Getting a similar error just now for a [very simple deployment](https://github.com/mrwweb/mrw-simplified-editor-wordpress/blob/release/.github/workflows/main.yml) (that doesn't even need a build):

> New tag
> Docker build failed with exit code 100
> New tag
> Docker build failed with exit code 100, back off 5.19 seconds before retry.
> New tag
> Docker build failed with exit code 100, back off 4.269 seconds before retry.

**Comment by helen** [comment]
Looks like some kind of container setup issue where something is not available in a registry, will try to get this figured out ASAP.

Edit: Documenting full error here for searchability:

```
  Step 2/4 : RUN apt-get update && apt-get install -y subversion rsync git zip && apt-get clean -y && rm -rf /var/lib/apt/lists/*
   ---> Running in 062aa1ab349c
  Ign:1 http://security.debian.org/debian-security stable/updates InRelease
  Get:2 http://deb.debian.org/debian stable InRelease [113 kB]
  Err:3 http://security.debian.org/debian-security stable/updates Release
    404  Not Found [IP: 151.101.130.132 80]
  Get:4 http://deb.debian.org/debian stable-updates InRelease [36.8 kB]
  Get:5 http://deb.debian.org/debian stable/main amd64 Packages [8178 kB]
  Reading package lists...
  E: The repository 'http://security.debian.org/debian-security stable/updates Release' does not have a Release file.
```

**Comment by weaver-sharethis** [comment]
Experienced the same thing this morning, so I forked temporarily and based the repo on `ubuntu:18.04`:

```
FROM ubuntu:18.04

RUN apt-get update \
	&& apt-get install -y subversion rsync git zip \
	&& apt-get clean -y \
	&& rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
```

Until things are sorted with the debian image, this works just fine.

**Comment by helen** [comment]
Yeah I wonder if it's temporary with the Debian image, really not sure what's going on here besides that I see there's no stable dist on security.debian. If switching to Ubuntu I feel like I should change this action to run directly on a runner and not spin up a container, as the ubuntu-latest runner comes pre-installed with everything I need... hopefully won't be a bad transition, will give it a shot this afternoon.

**Comment by tobeyadr** [comment]
> Experienced the same thing this morning, so I forked temporarily and based the repo on `ubuntu:18.04`:
> 
> ```
> FROM ubuntu:18.04
> 
> RUN apt-get update \
> 	&& apt-get install -y subversion rsync git zip \
> 	&& apt-get clean -y \
> 	&& rm -rf /var/lib/apt/lists/*
> 
> COPY entrypoint.sh /entrypoint.sh
> 
> ENTRYPOINT ["/entrypoint.sh"]
> ```
> 
> Until things are sorted with the debian image, this works just fine.

I just tried this and received the same issue... any thoughts?

**Comment by helen** [comment]
@tobeyadr What kind of additional thoughts are you looking for?

**Comment by tobeyadr** [comment]
@helen sorry, I'll be more specific. So I forked the action and made the change suggested by @weaver-sharethis. Setup my workflow to reference my forked repo however I'm still receiving the error you mentioned. I'm wondering if I set it up incorrectly or the ubuntu version is also affected by the issue with Debian. 

Trying to get a release out, should I just do it manually for now?

**Comment by helen** [comment]
@tobeyadr Looks like you need to reference the develop branch in yours for now, I am investigating running this as a composite action before just wholesale switching to Ubuntu, as I've always felt that spinning up an entire container for this is overly slow and expensive anyway.

**Comment by spacedmonkey** [comment]
Part of the issue here, the docker container is rebuilt on every build. Meaning, if there are issues upstream, builds will fail. A workaround for the future, is to build once and cache the built image somewhere. See https://github.com/10up/action-wordpress-plugin-deploy/issues/68 for more context.

**Comment by tobeyadr** [comment]
> @tobeyadr Looks like you need to reference the develop branch in yours for now, I am investigating running this as a composite action before just wholesale switching to Ubuntu, as I've always felt that spinning up an entire container for this is overly slow and expensive anyway.

@helen DUH! 🤦‍♂️ Works now, many thanks :)

**Comment by helen** [comment]
Working on this in #74 for now. The readme/asset updater will need the same treatment if this works.

**Comment by helen** [comment]
Just an update that this is actually working and it is _fast_, there is just an issue with the ZIP generation that I think is the root cause of #60 so I probably need to fix that as well while I'm in here.

**Comment by pablo-sg-pacheco** [comment]
Same problem here

**Comment by helen** [comment]
@pablo-sg-pacheco Are you in need of assistance? As documented above I am working on a fix, trying to ensure I don't break the ZIP generation.

**Comment by pablo-sg-pacheco** [comment]
Hi @helen ,
Yes, I'd like some help. How can I make it work before you complete the fix?
I'm sorry. I don't want to be a pain in the ass :)

**Comment by helen** [comment]
@pablo-sg-pacheco You can follow what others have done above or give me a couple hours to finish up and QA everything for release.

**Comment by pablo-sg-pacheco** [comment]
@helen , I still don't know what to do. But don't worry, take your time. I'll be waiting :)

**Comment by helen** [comment]
I've updated `stable` and tagged a `2.0.0`, could you all let me know if this works as expected? I tested various setups to attempt to catch any backcompat issues with existing workflow files but am a little worried there are variables I haven't accounted for.

**Comment by pablo-sg-pacheco** [comment]
It works for me @helen ,
Thanks!!

**Comment by roelmagdaleno** [comment]
@helen Works for me too! Thank you :)

**Comment by helen** [comment]
For future reference and anybody else experiencing this and desperately Googling, it appears it is because there was a new release of Debian and [the security repository moves](https://twitter.com/henrich/status/1427449488331874310), hence the 404. I cannot say I understand why this means `debian:stable-slim` should cease to work as it appears to be an official image to me and I almost certainly lifted that out of an early example Dockerfile, but it seems that in the meantime documentation has been updated to use names with version numbers. In any case, we ended up with a much better solution that I think will also set us on a better path to supporting deployment directories, time to apply this to the readme/asset updater.

**Comment by lipemat** [comment]
I wanted to say thank you for jumping on this and developing a solution so quickly. 

This action has streamlined a process and opened up new possibilities for development structure and workflow. When something which adds this much value has an issue and is then resolved in a day, it truly shows the commitment to community. I am grateful. 🙇

**Comment by weaver-sharethis** [comment]
@helen Haven't had a chance to test this yet, but also wanted to express gratitude for your quick turnaround time on it. Super helpful. 🚀
