### ISSUE TITLE
Mime type of .gif asset files are not updated

### ISSUE THREAD

**Issue by doekenorg** [helen/action-wordpress-plugin-deploy#75]
**Describe the bug**
Screenshots can be `.gif` files. These are useful for showing the interaction the user can expect. The mime-type of `.gif` files is not updated. So the file will be downloaded, instead of shown in the browser.

**Steps to Reproduce**
1. Create a repo with an assets folder that contains a `.gif` file
2. Run the action
3. Click the screenshot in the WordPress plugin page

**Expected behavior**
The file will open in the browser.

**Additional context**
PR added.

**Comment by jeffpaul** [comment]
Note that WP.org only states support for PNG or JPG filetypes for screenshots: https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#filenames-3.  Also, they do not state support for GIF for any plugin asset type for that matter.

**Comment by doekenorg** [comment]
> Note that WP.org only states support for PNG or JPG filetypes for screenshots: https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#filenames-3. Also, they do not state support for GIF for any plugin asset type for that matter.

**Comment by doekenorg** [comment]
Sorry,  working in my phone now and accidentally clicked the closing button.

It is pretty tucked away, but you can find a reference to this in the readme example. https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/#example-readme 

This is how I found it was possible.
