### ISSUE TITLE
Generated zip won't have plugin-slug folder inside

### ISSUE THREAD

**Issue by shivapoudel** [helen/action-wordpress-plugin-deploy#77]
**Describe the bug**
Seems like generated zip file while downloading won't have `plugin-slug` folder.

**Steps to Reproduce**

1. Implement github action with `generate-zip` enabled.
2. After all the process is complete, Open zip file!
4. See error, directly all files from trunk is located!

**Expected behavior**
ZIP file should have `plugin-slug`.

**Additional context**

**Comment by helen** [comment]
#72
