### ISSUE TITLE
Docs on ZIP need a refresh

### ISSUE THREAD

**Issue by KevinBatdorf** [helen/action-wordpress-plugin-deploy#81]
**Describe the bug**
The docs on generating and attaching a zip appear to not be the latest. 

https://github.com/10up/action-wordpress-plugin-deploy#deploy-on-publishing-a-new-release-and-attach-a-zip-file-to-the-release

I've changed mine from 
```
upload_url: ${{ github.event.release.upload_url }}
asset_path: ${{ steps.deploy.outputs.zip-path }}
asset_name: ${{ github.event.repository.name }}.zip
asset_content_type: application/zip
```

```
upload_url: ${{ github.event.release.upload_url }}
asset_path: ${{github.workspace}}/${{ github.event.repository.name }}.zip
asset_name: ${{ github.event.repository.name }}.zip
asset_content_type: application/zip
```

Which I gleaned from https://github.com/WordPress/theme-check/blob/master/.github/workflows/deploy.yml

But won't be able to confirm the change works until the next release cycle (wanted to report now though!)

Also, the repo [has a message](https://github.com/actions/upload-release-asset) that it's no longer maintained and to use https://github.com/softprops/action-gh-release instead. Has anyone tried swapping them out?

**Comment by KevinBatdorf** [comment]
The error message: 

> Error: Input required and not supplied: asset_path
![Screen Shot 2022-01-06 at 1 53 31 PM](https://user-images.githubusercontent.com/1478421/148435769-273f91c1-5f6b-4f86-8ee0-67d214f9264c.png)

Guessing that env variable is undefined now or something like that.

**Comment by jeffpaul** [comment]
@KevinBatdorf I ran some releases just last month that processed as expected using the `upload-release-asset` action, though it certainly seems a better step to take to update this example to use https://github.com/softprops/action-gh-release instead.  Happy to get a contributed PR through review if someone is able... thanks!

**Comment by KevinBatdorf** [comment]
I see the issue.`steps.deploy.outputs.zip-path` requires a step with an id of `deploy` ;-)

**Comment by jeffpaul** [comment]
@KevinBatdorf so ok to close this issue or is there a docs update to make that more clear for folks?

**Comment by KevinBatdorf** [comment]
Well it's up to you. It's still mentioning that archived repo. Can close it though if you prefer. I'll report back if there's ever an issue with our deployment zip attachment or if we end up switching to the newer one.

**Comment by jeffpaul** [comment]
Yeah for now it seems things are working as expected, but if that changes then we can look into replacing the archived repo reference with something else.
