### ISSUE TITLE
🛑  Other files have been modified; changes not deployed

### ISSUE THREAD

**Issue by faisal-alvi** [helen/action-wordpress-plugin-deploy#90]
**Describe the bug**
The action fails even when only the `readme.txt` file is changed.

Logs:
* https://github.com/10up/publisher-media-kit/runs/6384758988?check_suite_focus=true
* https://github.com/10up/publisher-media-kit/runs/6384736959?check_suite_focus=true

![image](https://user-images.githubusercontent.com/25176325/167989781-f49c8a93-6bce-4f3e-8af6-247e4331e6c0.png)
[image link](https://www.screencast.com/t/giDtWcNpk)

Relative commit: https://github.com/10up/publisher-media-kit/commit/beac3d91010768d6412699bcf9af53accca9182c

**Steps to Reproduce**

1. Change in `readme.txt.`
2. Commit & Push.
3. Action will fail, see the error.

**Expected behavior**
If only the `readme.txt` file is changed, the action should not fail and deployment to org should be done.

**Comment by KevinBatdorf** [comment]
Only looking at the image you maybe need to run your build script in the workflow?

**Comment by faisal-alvi** [comment]
Yes, already done it and it worked, I was about to post it here and saw your comment! :) 

Thanks for the help @iamdharmesh + @KevinBatdorf!
