### ISSUE TITLE
Directory out of date error

### ISSUE THREAD

**Issue by richard-muvirimi** [helen/action-wordpress-plugin-deploy#95]
**Describe the bug**

I get a directory out of date using the action for some strange reason. I did look into the possible causes and this [Stackover Issue](https://stackoverflow.com/a/3298401/5956589) seems to address the issue.

**Additional context**

This might be an svn related issue refusing to commit files because of a date mismatch. using bash only, I resolved this by just running `svn update` before the commit. I have not added the steps to reproduce as it happens on a fresh commit, might be times from git. Have attached a snippet of the error message.

```
➤ Committing files...
Adding         tags/1.0.4
svn: E155011: Commit failed (details follow):
svn: E155011: Directory '/home/runner/svn-force-reinstall/tags/1.0.4' is out of date
svn: E175014: Precondition on '/!svn/rvr/2733523/force-reinstall/trunk' failed
Error: Process completed with exit code 1.
```

**Comment by dinhtungdu** [comment]
In theory, we don't need to run `svn update` but if there are commits from other plugins that chime in, we'll need to sync again before committing.
